### PR TITLE
🔧 Update .travis.yml

### PR DESCRIPTION
**Pull request by Ghosin**
Add the curl command to trigger the synchronization API.

### CODE REVIEW

**Comment by Mitscherlich** [comment]
LGTM. So is there a environment variable named "SURL" in travis ci configuration?

**Comment by Ghosin** [comment]
Yes, the environment variable "SURL" is used to protect the updated API port from being directly exposed on the Internet.

**Comment by JunzhouLiu** [comment]
> Yes, the environment variable "SURL" is used to protect the updated API port from being directly exposed on the Internet.

But changing the CI environment variable only has permission for  @ChungZH . If he does not complete the configuration, the change will not be merged into the main repository for the time being.

**Comment by JunzhouLiu** [comment]
> Yes, the environment variable "SURL" is used to protect the updated API port from being directly exposed on the Internet.

Wait, it seems that we all have CI configuration permissions, or do you directly configure?

**Pull request closed without merging**
