### PR TITLE
🎀 Add new post: hexo-theme-plantom (fix #79)

### LINKED ISSUE #79: Hexo-theme-phantom 内容撰写
如有熟悉该主题的大佬，请速速领取任务。
~~任务奖励：风太大我听不见！~~
[Hexo-theme-phantom](https://github.com/klugjo/hexo-theme-phantom)
当然英文好的也可以翻译。[官方文档地址](https://github.com/klugjo/hexo-theme-phantom/blob/master/README.md)

### PR DESCRIPTION
**Pull request by GatesMa**
hexo-theme-plantom 主题安装及配置教程

fix #79

### CODE REVIEW

**Comment by JunzhouLiu** [comment]
CI check found that some image resource references are non-https methods .

**Comment by ChungZH** [comment]
> CI check found that some image resource references are non-https methods . This problem appears in 2-theme-use-and-config/2-14-hexo-theme-matery/index.html

收到

**Comment by yi-yun** [comment]
```
In 2-theme-use-and-config/2-14-hexo-theme-matery/index.html:

img http://static.blinkfox.com/matery-20181202-1.png
img http://static.blinkfox.com/matery-20181202-2.png
img http://static.blinkfox.com/matery-20181202-3.png
img http://static.blinkfox.com/matery-20181202-7.png
img http://static.blinkfox.com/matery-20181202-
```
有点强迫症……

**Comment by ChungZH** [comment]
图片那个要搬到本地，有点麻烦..让子弹飞一会儿

**Pull request merged**
